version: "3.9"

networks:
  web:
    driver: bridge
    name: web
  internal:
    external: false
    name: internal

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    restart: always
    volumes:
      - type: bind
        source: ./src
        target: /workspace
      - type: bind
        source: ./psysh
        target: /root/.config/psysh
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
    networks:
      - web
      - internal
  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    restart: always
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    depends_on:
      - db
    networks:
      - web
      - internal
  db:
    build:
      context: .
      dockerfile: ./infra/docker/pgsql/Dockerfile
    ports:
      - target: 5432
        published: ${DB_PUBLISHED_PORT:-5432}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./db
        target: /bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE:-laravel}
      - POSTGRESQL_USERNAME=${DB_USERNAME:-phper}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    ports:
      - target: 8025
        published: ${MAILHOG_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host
    networks:
      - internal
